---
title: "Course support"
---


## Lectures

If you have a question during lecture, feel free to ask it!
There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.


## Discussion forum

Prefer to write out your question in detail rather than asking in person?
The online discussion forum is the best venue for these!
We will use the [Moodle forum]() as the online discussion forum.
There is a chance another student has already asked a similar question, so please check the other posts before adding a new question.
If you know the answer to a question that is posted, I encourage you to respond!

## Email

Please refrain from emailing any course content questions (those should go to Moodle), and only use email for questions about personal matters that may not be appropriate for the public course forum. 
For such matters, you may email me at [kirenz@hdm-stuttgart.de](mailto:kirenz@hdm-stuttgart.de).

If there is a question that's not appropriate for the public forum, you are welcome to email me directly.
**If you email me, please include the name of our course in the subject line.** 

## Academic support

There are times you may need help with the class that is beyond what can be provided by the teaching team.
In those instances, I encourage you to visit the [**Center for Learning and Development**](https://www.hdm-stuttgart.de/studierende/abteilungen/cld/angebote_studierende_studieninteressierte): it offers free services to all students. 
