---
title: "Syllabus"
---

::: {.content-visible when-format="html"}
[**Click here**](syllabus.pdf) **to download a PDF copy of the syllabus.**
:::


## Course info

|           | Day       | Time              | Location |
|-----------|-----------|-------------------|----------|
| Lecture   | xyz    | xx:xx  - xx:xx xx |  xx  |



## Learning objectives

This course teaches you the fundamentals of 

By the end of the semester, you will be able to...




## Where to get help

- If you have a question during lecture, feel free to ask it! 
- Outside of class, any general questions about course content or assignments should be posted on the Moodle course forum.
- Emails should be reserved for questions not appropriate for the public forum. **If you email me, please include the name of our course in the subject line.** 

Check out the [Support](course-support.qmd) page for more resources.

## Textbooks

This course is mainly based on the following resources:



## Lectures

A lot of what you do in this course will involve writing code, and coding is a skill that is best learned by doing.
Therefore, as much as possible, you will be working on a variety of tasks and activities throughout each lecture.

You are expected to bring a laptop to each class so that you can take part in the in-class exercises.


## Teams

You will be assigned to a team at the beginning of the semester.

All team members are expected to contribute equally to the completion of the labs and project and you will be asked to evaluate your team members throughout the semester.
Failure to adequately contribute to an assignment will result in a penalty to your mark relative to the team's overall mark.

You are expected to make use of the provided GitHub repository as the central collaborative platform. [Commits](https://github.com/git-guides/git-commit) to this repository will be used as a metric (one of several) of each team member's relative contribution for each project.

## Assessment

Assessment for the course is comprised of these components: 

- [application exercises](@sec-application-exercises)
- [homework assignments](@sec-hw) 
- [project](@sec-project)


### Application exercises {#sec-application-exercises}

Parts of some lectures will be dedicated to working on "Application Exercises" (AE). These small exercises will give you an opportunity to practice apply the concepts and code introduced in the readings and lectures. 

AEs should be completed and **submitted individually**.

:::{Note}
AEs are due within six days after lecture
:::

The AEs are due within **six days** after the corresponding lecture. For example, AEs from a Monday lecture would be due Sunday by 11:59 pm.

Because these AEs are for practice, they will be graded based on completion. Successful on-time completion of at least 80% of every AE will result in full credit in the final course grade. 


### Homework {#sec-hw}

In homeworks (HW), you will apply what you've learned during lectures to complete data analysis and visualization‚ tasks using data not covered during lectures.

You may discuss homework assignments with other students; however, homework should be completed and **submitted individually**.

Homework must be completed in the provided Jupyter Notebooks in your course GitHub-repo and also submitted in Moodle.



### Exams {#sec-exams}

There will be two exams in Moodle.
Through these exams you have the opportunity to demonstrate what you've learned in the course thus far.


More details about the exams will be given during the semester.



### Project {#sec-project}

The purpose of the [project](project-description.qmd) is to apply what you've learned throughout the semester to analyze an interesting, data-driven research question. The project will be completed in **teams**.

More information about the project will be provided during the semester.

## Grading

The final course grade will be calculated as follows:

| Category              | Percentage      |
|-----------------------|-----------------|
| Application exercises | 10%             |
| Homework              | 40%             |
| Project               | 50%             |


The final grade will be determined based on the following thresholds:

|  Grade       | Final Course Grade |
|--------------|--------------------|
| 1.0           | 96 - 100          |
| 1.3           | 91 - 95           |
| 1.7           | 85 - 90           |
| 2.0           | 80 - 84           |
| 2.3           | 75 - 79           |
| 2.7           | 70 - 74           |
| 3.0           | 65 - 69           |
| 3.3           | 60 - 64           |
| 3.7           | 55 - 59           |
| 4.0            | 50 - 54          |
| 4.7           | 15 - 49           |
| 5.0            | 0 - 14           |



## Course policies

### Academic integrity

**TL;DR: Don't cheat!**

All students must adhere to the academic integrity standard. Students affirm their commitment to uphold the values by signing a pledge that states:

-   I will not lie, cheat, or steal in my academic endeavors;
-   I will conduct myself honorably in all my endeavors;
-   I will act if the standard is compromised

Regardless of the course delivery format, it is your responsibility to understand and follow HdM policies regarding academic integrity, including doing one's own work, following proper citation of sources, and adhering to guidance around group work projects.


### Collaboration policy

Only work that is clearly assigned as team work should be completed collaboratively.

-   The *homework* assignments must be completed individually and you are welcomed to discuss the assignment with classmates at a high level (e.g., discuss what's the best way for approaching a problem, what functions are useful for accomplishing a particular task, etc.). However you may not directly share answers to homework questions (including any code) with anyone other than myself and the teaching assistants.

-   For the *projects*, collaboration within teams is not only allowed, but expected. Communication between teams at a high level is also allowed however you may not share code or components of the project across teams.


### Policy on sharing and reusing code

I am well aware that a huge volume of code is available on the web to solve any number of problems.

Unless I explicitly tell you not to use something, the course's policy is that you may make use of any online resources (e.g. [StackOverflow](https://stackoverflow.com/)) but you must explicitly cite where you obtained any code you directly use (or use as inspiration).

Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

On individual assignments you may not directly share code with another student in this class, and on team assignments you may not directly share code with another team in this class.

### Late work policy

The due dates for assignments are there to help you keep up with the course material. However, I understand that things come up periodically that could make it difficult to submit an assignment by the deadline. Here are the rules for late submissions:

-   *Homeworks* may be submitted up to 3 days late.
    There will be a 25% deduction for each 24-hour period the assignment is late.

-   There is no late work accepted for *application exercises*, since these are designed to help you prepare for homeworks.

-   Project taks may be submitted up to 2 days late. There will be a 25% deduction for each 24-hour period the project task is late.

If there are important circumstances that prevent you from completing a lab or homework assignment by the stated due date, you may email me at [kirenz@hdm-stuttgart.de](mailto:kirenz@hdm-stuttgart.de) before the deadline.